#ifndef ANGLE_SHADER_PROGRAM_VERSION_H_
#define ANGLE_SHADER_PROGRAM_VERSION_H_

#define ANGLE_PROGRAM_VERSION "roon-vis-angle-metal-tvos-step-a"
#define ANGLE_PROGRAM_VERSION_HASH_SIZE 34

#endif  // ANGLE_SHADER_PROGRAM_VERSION_H_
