#!/usr/bin/env bash
#
# pi-setup.sh — one-shot Raspberry Pi bootstrap for RoonVis
#
# Installs and configures the audio-capture side of RoonVis on a Raspberry Pi:
#   * RoonBridge          (so Roon can stream to this Pi)
#   * Snapcast server     (snapserver — streams the captured PCM to the Apple TV)
#   * snd-aloop loopback  (the ALSA "virtual cable" Roon plays into and snapserver reads)
#
# After this script finishes there are a few things it CANNOT do for you — they live
# inside the Roon app UI. The script prints them at the end (authorise RoonBridge,
# enable the loopback as an audio zone + group it with your speakers, and turn on
# 44.1 kHz sample-rate conversion in Roon's DSP engine "MUSE"). See the wiki:
# Setup-Roon-Pi-Snapcast.
#
# Safe to re-run (idempotent). Backs up any existing /etc/snapserver.conf to
# /etc/snapserver.conf.orig before writing. Requires sudo.
#
# Tested target: Raspberry Pi OS (64-bit, arm64). RoonBridge requires a 64-bit OS.

set -euo pipefail

SNAPCONF="/etc/snapserver.conf"
MODCONF="/etc/modules-load.d/snd-aloop.conf"
ROON_INSTALLER_URL="http://download.roonlabs.com/builds/roonbridge-installer-linuxarmv8.sh"

log()  { printf '\033[1;36m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[!]\033[0m %s\n' "$*"; }
die()  { printf '\033[1;31m[x]\033[0m %s\n' "$*" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || die "Please run with sudo:  sudo bash pi-setup.sh"
command -v apt-get >/dev/null 2>&1 || die "This script targets Debian/Raspberry Pi OS (apt-get not found)."
[ "$(uname -m)" = "aarch64" ] || warn "Not arm64 (uname -m = $(uname -m)); RoonBridge needs a 64-bit OS."

# --------------------------------------------------------------------------------------
# 1. snd-aloop loopback — load now + on every boot
# --------------------------------------------------------------------------------------
log "Configuring snd-aloop ALSA loopback"
if [ ! -f "$MODCONF" ] || ! grep -q '^snd-aloop$' "$MODCONF" 2>/dev/null; then
  echo "snd-aloop" > "$MODCONF"
  log "  wrote $MODCONF"
else
  log "  $MODCONF already present"
fi
modprobe snd-aloop || die "modprobe snd-aloop failed"
[ -d /proc/asound/Loopback ] || die "Loopback device did not appear after modprobe"
log "  loopback active (/proc/asound/Loopback)"

# --------------------------------------------------------------------------------------
# 2. Snapcast server
# --------------------------------------------------------------------------------------
log "Installing snapserver"
if ! command -v snapserver >/dev/null 2>&1; then
  apt-get update -y
  if ! apt-get install -y snapserver; then
    warn "apt install snapserver failed — falling back to the GitHub .deb"
    ARCH="$(dpkg --print-architecture)"
    TMP_DEB="$(mktemp --suffix=.deb)"
    # Pin a known-good release; bump if you want a newer snapserver.
    DEB_URL="https://github.com/badaix/snapcast/releases/download/v0.27.0/snapserver_0.27.0-1_${ARCH}_bullseye.deb"
    log "  downloading $DEB_URL"
    curl -fL "$DEB_URL" -o "$TMP_DEB" || die "Could not download snapserver .deb for $ARCH"
    apt-get install -y "$TMP_DEB"
    rm -f "$TMP_DEB"
  fi
else
  log "  snapserver already installed ($(snapserver --version 2>/dev/null | head -1))"
fi

# --------------------------------------------------------------------------------------
# 3. snapserver.conf — the proven RoonVis config
#    (reads the DEV=1 capture end of snd-aloop; 44.1 kHz / 16-bit / stereo PCM)
# --------------------------------------------------------------------------------------
log "Writing $SNAPCONF"
if [ -f "$SNAPCONF" ] && [ ! -f "${SNAPCONF}.orig" ]; then
  cp -a "$SNAPCONF" "${SNAPCONF}.orig"
  log "  backed up existing config → ${SNAPCONF}.orig"
fi
cat > "$SNAPCONF" <<'EOF'
# RoonVis snapserver config (generated by pi-setup.sh)
# Source = the DEV=1 capture end of the snd-aloop loopback. Roon plays into the
# DEV=0 playback end (see the wiki: the counter-intuitive "which Loopback end" gotcha).
# send_silence keeps the Apple TV client's clock synced when nothing is playing.
[stream]
source = alsa://?name=Roon&device=plughw:Loopback,1,0&sampleformat=44100:16:2&codec=pcm&chunk_ms=10&send_silence=true&idle_threshold=30000
buffer = 50
codec = pcm
sampleformat = 44100:16:2
chunk_ms = 10

[http]
enabled = true

[tcp]
enabled = true
EOF

# --------------------------------------------------------------------------------------
# 4. RoonBridge
# --------------------------------------------------------------------------------------
log "Installing RoonBridge"
if [ ! -x /opt/RoonBridge/start.sh ] && ! systemctl list-unit-files 2>/dev/null | grep -qi roonbridge; then
  TMP_SH="$(mktemp --suffix=.sh)"
  curl -fL "$ROON_INSTALLER_URL" -o "$TMP_SH" || die "Could not download the RoonBridge installer"
  bash "$TMP_SH"
  rm -f "$TMP_SH"
else
  log "  RoonBridge already installed"
fi

# --------------------------------------------------------------------------------------
# 5. Enable + (re)start services
# --------------------------------------------------------------------------------------
log "Enabling + starting services"
systemctl enable --now snapserver >/dev/null 2>&1 || warn "could not enable snapserver via systemd"
systemctl restart snapserver     >/dev/null 2>&1 || warn "could not restart snapserver"
systemctl restart roonbridge     >/dev/null 2>&1 || true

# --------------------------------------------------------------------------------------
# Done — print the Pi's IP + the manual Roon steps
# --------------------------------------------------------------------------------------
PI_IP="$(hostname -I 2>/dev/null | awk '{print $1}')"
cat <<EOF

$(printf '\033[1;32m✓ RoonVis Pi setup complete.\033[0m')

  Snapcast server IP : ${PI_IP:-<this-pi-ip>}   (port 1704)
  → set this as SnapcastServerHost in the RoonVis app (Info.plist / build config)

Now finish the setup inside the Roon app (the script cannot do these for you):

  1. Settings → Audio: find this Pi and enable/authorise "RoonBridge".
  2. Enable the snd-aloop "Loopback" output as an audio zone, and GROUP it with
     your speakers so it receives the same audio.
       • Roon lists TWO identical "Loopback" outputs (the two ends of snd-aloop).
         The CORRECT one is the end that appears to *pause immediately* when you
         play to it — that is the DEV=0 playback end snapserver is listening to.
  3. For that zone, open Roon's DSP engine (MUSE) and enable
     Sample Rate Conversion → fixed 44.1 kHz.
       • Why: snd-aloop locks both ends to snapserver's 44.1 kHz, so Roon's default
         48 kHz open is rejected. MUSE converts the stream to 44.1 kHz.

Verify the stream is live:
  curl / snapcast control API — Server.GetStatus on ${PI_IP:-<this-pi-ip>}:1705,
  stream "Roon" status should be "playing" when music is playing (not "idle").

Full guide: the project wiki → Setup-Roon-Pi-Snapcast.
EOF
